<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Qwiq</RootNamespace>
    <CodeAnalysisRuleSet>..\..\build\rulesets\noship.ruleset</CodeAnalysisRuleSet>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitVersionTask" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" />
    <PackageReference Include="Microsoft.TeamFoundation.DistributedTask.Common" />
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" />
    <PackageReference Include="Microsoft.TeamFoundationServer.ExtendedClient" />
    <PackageReference Include="Microsoft.Tpl.Dataflow" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" />
    <PackageReference Include="Microsoft.VisualStudio.Services.InteractiveClient" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Should" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="WindowsAzure.ServiceBus" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  <Choose>
    <When Condition="('$(VisualStudioVersion)' == '10.0' or '$(VisualStudioVersion)' == '') and '$(TargetFrameworkVersion)' == 'v3.5'">
      <ItemGroup>
        <Reference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" />
      </ItemGroup>
    </When>
    <Otherwise />
  </Choose>
  <ItemGroup>
    <Compile Include="..\..\src\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Qwiq.Core.Soap\Qwiq.Client.Soap.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\Qwiq.Mocks\Qwiq.Mocks.csproj" />
    <ProjectReference Include="..\Qwiq.Tests.Common\Qwiq.Tests.Common.csproj" />
  </ItemGroup>
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '10.0' And '$(IsCodedUITest)' == 'True'">
      <ItemGroup>
        <Reference Include="Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Extension, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITesting, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
</Project>