<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\packages\UtilPack.NuGet.MSBuild.2.8.0\build\UtilPack.NuGet.MSBuild.props" Condition="Exists('..\..\packages\UtilPack.NuGet.MSBuild.2.8.0\build\UtilPack.NuGet.MSBuild.props')" />
  <Import Project="..\..\build\targets\common.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core.Soap\Qwiq.Client.Soap.csproj" />
    <ProjectReference Include="..\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\Qwiq.Identity\Qwiq.Identity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="5.12.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.3" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.13.9" /><PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="19.225.1" />
    <PackageReference Include="Microsoft.TeamFoundationServer.ExtendedClient" Version="15.112.1" />
    <PackageReference Include="Microsoft.Tpl.Dataflow" Version="4.5.24" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="19.225.1" />
    <PackageReference Include="Microsoft.VisualStudio.Services.InteractiveClient" Version="19.225.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="UtilPack.NuGet.MSBuild" Version="2.8.0" />
    <PackageReference Include="WindowsAzure.ServiceBus" Version="3.3.2" />
  </ItemGroup></Project>
