<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>Qwiq.Identity.Soap</RootNamespace>
    <AssemblyName>Qwiq.Identity.Soap</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.3" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.3" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.13.9" />
    <PackageReference Include="Microsoft.TeamFoundation.DistributedTask.Common" Version="15.112.1" />
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="15.112.1" />
    <PackageReference Include="Microsoft.TeamFoundationServer.ExtendedClient" Version="15.112.1" />
    <PackageReference Include="Microsoft.Tpl.Dataflow" Version="4.5.24" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="15.112.1" />
    <PackageReference Include="Microsoft.VisualStudio.Services.InteractiveClient" Version="15.112.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="4.0.4.403061554" />
    <PackageReference Include="WindowsAzure.ServiceBus" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core.Soap\Qwiq.Client.Soap.csproj" />
    <ProjectReference Include="..\Qwiq.Identity\Qwiq.Identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs" Link="Properties\AssemblyInfo.Common.cs" />
    <Compile Include="..\ReSharper.Annotations.cs" Link="Properties\ReSharper.Annotations.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Qwiq.Identity.Soap.nuspec">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

</Project>
