<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Qwiq.Identity</RootNamespace>
    <CodeAnalysisRuleSet>..\..\build\rulesets\noship.ruleset</CodeAnalysisRuleSet>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitVersionTask" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" />
    <PackageReference Include="Microsoft.TeamFoundation.DistributedTask.Common" />
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" />
    <PackageReference Include="Microsoft.TeamFoundationServer.ExtendedClient" />
    <PackageReference Include="Microsoft.Tpl.Dataflow" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" />
    <PackageReference Include="Microsoft.VisualStudio.Services.InteractiveClient" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Should" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="WindowsAzure.ServiceBus" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\src\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Identity\Qwiq.Identity.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Identity.Soap\Qwiq.Identity.Soap.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Mapper\Qwiq.Mapper.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Mapper.Identity\Qwiq.Mapper.Identity.csproj" />
    <ProjectReference Include="..\Qwiq.Mocks\Qwiq.Mocks.csproj" />
    <ProjectReference Include="..\Qwiq.Tests.Common\Qwiq.Tests.Common.csproj" />
  </ItemGroup>
</Project>