<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    
    <!-- Nullable reference types warnings -->
    <WarningLevel>5</WarningLevel>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    
    <!-- Shared assembly information -->
    <Company>Microsoft Corporation</Company>
    <Product>Microsoft® Quick Work Item Queries</Product>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    
    <!-- Let NBGV handle version attributes -->
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <!-- Add Nerdbank.GitVersioning for all projects -->
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    
    <!-- Add Microsoft.CodeAnalysis.NetAnalyzers to replace deprecated FxCop -->
    <!-- See: https://learn.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-net-analyzers -->
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" PrivateAssets="all" />
  </ItemGroup>
</Project>
