<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>Qwiq.Linq</RootNamespace>
    <AssemblyName>Qwiq.Linq.Identity</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Identity\Qwiq.Identity.csproj" />
    <ProjectReference Include="..\Qwiq.Linq\Qwiq.Linq.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs" Link="Properties\AssemblyInfo.Common.cs" />
    <Compile Include="..\ReSharper.Annotations.cs" Link="Properties\ReSharper.Annotations.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="Qwiq.Linq.Identity.nuspec" />
  </ItemGroup>

</Project>
