<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>Qwiq.Linq</RootNamespace>
    <AssemblyName>Qwiq.Linq.Identity</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Identity\Qwiq.Identity.csproj" />
    <ProjectReference Include="..\Qwiq.Linq\Qwiq.Linq.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs" Link="Properties\AssemblyInfo.Common.cs" />
    <Compile Include="..\ReSharper.Annotations.cs" Link="Properties\ReSharper.Annotations.cs" />
  </ItemGroup>

</Project>
