<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\noship.ruleset</CodeAnalysisRuleSet>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BenchmarkDotNet.Core" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" />
    <PackageReference Include="BenchmarkDotNet.Toolchains.Roslyn" />
    <PackageReference Include="GitVersionTask" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
    <PackageReference Include="Microsoft.DotNet.InternalAbstractions" />
    <PackageReference Include="Microsoft.DotNet.PlatformAbstractions" />
    <PackageReference Include="Microsoft.Win32.Registry" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="System.AppContext" />
    <PackageReference Include="System.Collections" />
    <PackageReference Include="System.Collections.Concurrent" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Console" />
    <PackageReference Include="System.Diagnostics.Debug" />
    <PackageReference Include="System.Diagnostics.FileVersionInfo" />
    <PackageReference Include="System.Diagnostics.StackTrace" />
    <PackageReference Include="System.Diagnostics.Tools" />
    <PackageReference Include="System.Dynamic.Runtime" />
    <PackageReference Include="System.Globalization" />
    <PackageReference Include="System.IO.Compression" />
    <PackageReference Include="System.IO.FileSystem" />
    <PackageReference Include="System.IO.FileSystem.Primitives" />
    <PackageReference Include="System.Linq" />
    <PackageReference Include="System.Linq.Expressions" />
    <PackageReference Include="System.Reflection" />
    <PackageReference Include="System.Reflection.Metadata" />
    <PackageReference Include="System.Reflection.Primitives" />
    <PackageReference Include="System.Resources.ResourceManager" />
    <PackageReference Include="System.Runtime" />
    <PackageReference Include="System.Runtime.Extensions" />
    <PackageReference Include="System.Runtime.Handles" />
    <PackageReference Include="System.Runtime.InteropServices" />
    <PackageReference Include="System.Runtime.Numerics" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" />
    <PackageReference Include="System.Security.Cryptography.Encoding" />
    <PackageReference Include="System.Security.Cryptography.Primitives" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" />
    <PackageReference Include="System.Text.Encoding" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
    <PackageReference Include="System.Text.Encoding.Extensions" />
    <PackageReference Include="System.Threading" />
    <PackageReference Include="System.Threading.Tasks" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
    <PackageReference Include="System.Threading.Tasks.Parallel" />
    <PackageReference Include="System.Threading.Thread" />
    <PackageReference Include="System.ValueTuple" />
    <PackageReference Include="System.Xml.ReaderWriter" />
    <PackageReference Include="System.Xml.XDocument" />
    <PackageReference Include="System.Xml.XmlDocument" />
    <PackageReference Include="System.Xml.XmlSerializer" />
    <PackageReference Include="System.Xml.XPath" />
    <PackageReference Include="System.Xml.XPath.XDocument" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Management" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\src\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Tests.Common\Qwiq.Tests.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="TraceEvent.ReadMe.txt" />
    <Content Include="TraceEvent.ReleaseNotes.txt" />
  </ItemGroup>
</Project>