<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\targets\common.props" />
  <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\noship.ruleset</CodeAnalysisRuleSet>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.10.11" />
    <PackageReference Include="BenchmarkDotNet.Core" Version="0.10.11" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.10.11" />
    <PackageReference Include="BenchmarkDotNet.Toolchains.Roslyn" Version="0.10.11" />
    <PackageReference Include="GitVersionTask" Version="4.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="1.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="2.6.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.6.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="1.0.41" />
    <PackageReference Include="Microsoft.DotNet.InternalAbstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.DotNet.PlatformAbstractions" Version="2.0.4" />
    <PackageReference Include="Microsoft.Net.Compilers" Version="2.10.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
    <PackageReference Include="System.AppContext" Version="4.3.0" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.Collections.Immutable" Version="1.4.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="9.0.9" />
    <PackageReference Include="System.Console" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.FileVersionInfo" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.StackTrace" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Tools" Version="4.3.0" />
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="System.Globalization" Version="4.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
    <PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
    <PackageReference Include="System.Management" Version="9.0.9" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Metadata" Version="1.5.0" />
    <PackageReference Include="System.Reflection.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Resources.ResourceManager" Version="4.3.0" />
    <PackageReference Include="System.Runtime" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Numerics" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.Encoding" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="System.Text.Encoding" Version="4.3.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.4.0" />
    <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Threading" Version="4.3.0" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.4.0" />
    <PackageReference Include="System.Threading.Tasks.Parallel" Version="4.3.0" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
    <PackageReference Include="System.Xml.ReaderWriter" Version="4.3.1" />
    <PackageReference Include="System.Xml.XDocument" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
    <PackageReference Include="System.Xml.XPath" Version="4.3.0" />
    <PackageReference Include="System.Xml.XPath.XDocument" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\src\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Tests.Common\Qwiq.Tests.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="TraceEvent.ReadMe.txt" />
    <Content Include="TraceEvent.ReleaseNotes.txt" />
  </ItemGroup>
</Project>