<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
    <Compile Include="..\ReSharper.Annotations.cs">
      <Link>Properties\ReSharper.Annotations.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core\Qwiq.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitVersionTask" />
    <PackageReference Include="Microsoft.Net.Compilers" />
    <PackageReference Include="UtilPack.NuGet.MSBuild" />
  </ItemGroup>
</Project>