<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>Qwiq.Linq</RootNamespace>
    <AssemblyName>Qwiq.Linq</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core\Qwiq.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs" Link="Properties\AssemblyInfo.Common.cs" />
  </ItemGroup>

</Project>
