<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>Qwiq.Linq</RootNamespace>
    <AssemblyName>Qwiq.Linq</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core\Qwiq.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs" Link="Properties\AssemblyInfo.Common.cs" />
    <Compile Include="..\ReSharper.Annotations.cs" Link="Properties\ReSharper.Annotations.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="Qwiq.Linq.nuspec" />
  </ItemGroup>

</Project>
