<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>Microsoft.Qwiq.Tests.Common</RootNamespace>
    <AssemblyName>Microsoft.Qwiq.Tests.Common</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
    <CodeAnalysisRuleSet>..\..\build\rulesets\noship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer.Core" Version="2.2.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
    <PackageReference Include="Should" Version="1.1.20" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\src\AssemblyInfo.Common.cs" Link="Properties\AssemblyInfo.Common.cs" />
    <Compile Include="..\..\src\Qwiq.Core\Extensions.cs" Link="Extensions.cs" />
    <Compile Include="..\..\src\Qwiq.Core\GenericComparer.cs" Link="GenericComparer.cs" />
    <Compile Include="..\..\src\ReSharper.Annotations.cs" Link="Properties\ReSharper.Annotations.cs" />
  </ItemGroup>

</Project>
