<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Qwiq.Integration.Tests</RootNamespace>
    <AssemblyName>Qwiq.IntegrationTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.DotMemoryUnit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Should" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Core.Rest\Qwiq.Client.Rest.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Identity\Qwiq.Identity.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Linq\Qwiq.Linq.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Mapper\Qwiq.Mapper.csproj" />
    <ProjectReference Include="..\Qwiq.Mocks\Qwiq.Mocks.csproj" />
    <ProjectReference Include="..\Qwiq.Tests.Common\Qwiq.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\src\AssemblyInfo.Common.cs" Link="Properties\AssemblyInfo.Common.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Identity\**\*.cs" />
    <Compile Remove="IntegrationSettings.cs" />
    <Compile Remove="Linq\**\*.cs" />
    <Compile Remove="Mapper\**\*.cs" />
    <Compile Remove="Project\**\*.cs" />
    <Compile Remove="WorkItemStore\**\*.cs" />
  </ItemGroup>

</Project>
