<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Qwiq.Mapper</RootNamespace>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile>$(OutputPath)Microsoft.Qwiq.Mapper.Identity.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\Qwiq.Mapper.Identity.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DocumentationFile>bin\Release\Qwiq.Mapper.Identity.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\Qwiq.Identity\Qwiq.Identity.csproj" />
    <ProjectReference Include="..\Qwiq.Linq\Qwiq.Linq.csproj" />
    <ProjectReference Include="..\Qwiq.Mapper\Qwiq.Mapper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FastMember" Version="1.1.0" />
    <PackageReference Include="GitVersionTask" Version="4.0.0" />
    <PackageReference Include="Microsoft.Net.Compilers" Version="2.10.0" />
    <PackageReference Include="UtilPack.NuGet.MSBuild" Version="2.8.0" />
  </ItemGroup>
</Project>