<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>  </PropertyGroup>  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\Qwiq.Linq\Qwiq.Linq.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FastMember" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />


  </ItemGroup>
</Project>