<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\Qwiq.Identity.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DocumentationFile>bin\Release\Qwiq.Identity.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
    <Compile Include="..\ReSharper.Annotations.cs">
      <Link>Properties\ReSharper.Annotations.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qwiq.Core\Qwiq.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitVersionTask" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="Microsoft.Net.Compilers" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" />
    <PackageReference Include="Newtonsoft.Json" />

  </ItemGroup>
</Project>