<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Qwiq</RootNamespace>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
    <RunCodeAnalysis>true</RunCodeAnalysis>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web.Services" />
  </ItemGroup>
  
  <!-- InternalsVisibleTo declarations for testing and client libraries -->
  <ItemGroup>
    <InternalsVisibleTo Include="Qwiq.Core.UnitTests" />
    <InternalsVisibleTo Include="Qwiq.Mocks" />
    <InternalsVisibleTo Include="Qwiq.Client.Soap" />
    <InternalsVisibleTo Include="Qwiq.Client.Rest" />
    <InternalsVisibleTo Include="Qwiq.Integration.Tests" />
    <InternalsVisibleTo Include="Qwiq.Relatives.Tests" />
    <InternalsVisibleTo Include="Qwiq.IntegrationTests" />
    <InternalsVisibleTo Include="Qwiq.Identity.Soap" />
    <InternalsVisibleTo Include="Qwiq.Mapper" />
    <InternalsVisibleTo Include="Qwiq.Mapper.Identity" />
    <InternalsVisibleTo Include="Qwiq.Identity.UnitTests" />
    <InternalsVisibleTo Include="Microsoft.Qwiq.Tests.Common" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Qwiq.Core.nuspec">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" />

    <PackageReference Include="Microsoft.VisualStudio.Services.Client" />
    <PackageReference Include="Microsoft.VisualStudio.Services.InteractiveClient" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />

    <PackageReference Include="WindowsAzure.ServiceBus" />
  </ItemGroup>
</Project>