<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Qwiq</RootNamespace>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
    <RunCodeAnalysis>true</RunCodeAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web.Services" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
    <Compile Include="..\ReSharper.Annotations.cs">
      <Link>Properties\ReSharper.Annotations.cs</Link>
    </Compile>
    <Compile Update="IWorkItemLinkInfo.Extensions.cs">
      <DependentUpon>IWorkItemLinkInfo.cs</DependentUpon>
    </Compile>
    <Compile Update="IWorkItemLinkType.Extensions.cs">
      <DependentUpon>IWorkItemLinkType.cs</DependentUpon>
    </Compile>
    <Compile Update="IWorkItemLinkTypeEnd.Extensions.cs">
      <DependentUpon>IWorkItemLinkTypeEnd.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Qwiq.Core.nuspec">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="GitVersionTask" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" />
    <PackageReference Include="Microsoft.Net.Compilers" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" />
    <PackageReference Include="Microsoft.VisualStudio.Services.InteractiveClient" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="UtilPack.NuGet.MSBuild" />
    <PackageReference Include="WindowsAzure.ServiceBus" />
  </ItemGroup>
</Project>