<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>  <ItemGroup>
    <ProjectReference Include="..\..\src\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Identity\Qwiq.Identity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />

    <PackageReference Include="Microsoft.VisualStudio.Services.Client" />
    <PackageReference Include="Newtonsoft.Json" />

  </ItemGroup>
</Project>