<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>Library</OutputType>
    <CodeAnalysisRuleSet>..\..\build\rulesets\ship.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\AssemblyInfo.Common.cs">
      <Link>Properties\AssemblyInfo.Common.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Qwiq.Core\Qwiq.Core.csproj" />
    <ProjectReference Include="..\..\src\Qwiq.Identity\Qwiq.Identity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitVersionTask" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.3" />
    <PackageReference Include="Microsoft.Net.Compilers" Version="2.10.0" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="15.112.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="UtilPack.NuGet.MSBuild" Version="2.8.0" />
  </ItemGroup>
</Project>